import path from "path";
import fs from "fs";
import { NextResponse } from "next/server";
import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";
import { prisma } from "@/lib/prisma";
import { getYahrzeitDates, type YahrzeitEntry } from "@/lib/yahrzeit";

type Params = { id: string };

// Disable WebGL — not needed for PDF rendering
chromium.setGraphicsMode = false;

// ─── Labels ──────────────────────────────────────────────────────────────────

type PdfLabels = {
  title: string;
  deathDatePrefix: string;
  colYear: string;
  colHebrewDate: string;
  colGregorianDate: string;
  footer: string;
  dateLocale: string;
};

const EN_LABELS: PdfLabels = {
  title: "Yahrzeit Calendar",
  deathDatePrefix: "Hebrew date of passing:",
  colYear: "Year",
  colHebrewDate: "Hebrew Date",
  colGregorianDate: "Gregorian Date",
  footer: `Generated by Forever Memorial \u2022 ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
  dateLocale: "en-US",
};

const HE_LABELS: PdfLabels = {
  title: "\u05DC\u05D5\u05D7 \u05D9\u05D0\u05E8\u05E6\u05D9\u05D9\u05D8",
  deathDatePrefix:
    "\u05EA\u05D0\u05E8\u05D9\u05DA \u05E4\u05D8\u05D9\u05E8\u05D4 \u05E2\u05D1\u05E8\u05D9:",
  colYear: "\u05E9\u05E0\u05D4",
  colHebrewDate:
    "\u05EA\u05D0\u05E8\u05D9\u05DA \u05E2\u05D1\u05E8\u05D9",
  colGregorianDate:
    "\u05EA\u05D0\u05E8\u05D9\u05DA \u05DC\u05D5\u05E2\u05D6\u05D9",
  footer: `\u05E0\u05D5\u05E6\u05E8 \u05E2\u05DC \u05D9\u05D3\u05D9 Forever Memorial \u2022 ${new Date().toLocaleDateString("he-IL", { year: "numeric", month: "long", day: "numeric" })}`,
  dateLocale: "he-IL",
};

// ─── ICS ─────────────────────────────────────────────────────────────────────

function formatIcsDate(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}${m}${d}`;
}

function nextDay(date: Date): string {
  const next = new Date(date);
  next.setDate(next.getDate() + 1);
  return formatIcsDate(next);
}

function generateICS(
  memorialId: string,
  name: string,
  entries: ReturnType<typeof getYahrzeitDates>
): string {
  const dtstamp =
    new Date().toISOString().replace(/[-:.]/g, "").slice(0, 15) + "Z";

  const events = entries
    .map((entry, i) => {
      const dateStr = formatIcsDate(entry.gregorianDate);
      const endStr = nextDay(entry.gregorianDate);
      return [
        "BEGIN:VEVENT",
        `UID:yahrzeit-${memorialId}-${i}@forever-memorial`,
        `DTSTAMP:${dtstamp}`,
        `DTSTART;VALUE=DATE:${dateStr}`,
        `DTEND;VALUE=DATE:${endStr}`,
        `SUMMARY:Yahrzeit \u2014 ${name}`,
        `DESCRIPTION:${entry.hebrewDate}`,
        "END:VEVENT",
      ].join("\r\n");
    })
    .join("\r\n");

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Forever Memorial//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    events,
    "END:VCALENDAR",
  ].join("\r\n");
}

// ─── PDF ─────────────────────────────────────────────────────────────────────

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatGregorianDate(date: Date, dateLocale: string): string {
  return date.toLocaleDateString(dateLocale, {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

const FONT_DIR = path.join(process.cwd(), "src/fonts");

function buildFontFace(file: string, weight: string): string {
  const p = path.join(FONT_DIR, file);
  if (!fs.existsSync(p)) return "";
  const b64 = fs.readFileSync(p).toString("base64");
  return `@font-face{font-family:'FRLibre';src:url('data:font/truetype;base64,${b64}')format('truetype');font-weight:${weight};}`;
}

function buildHtml(
  name: string,
  hebrewDeathDate: string,
  entries: YahrzeitEntry[],
  labels: PdfLabels
): string {
  const isHebrew = labels.dateLocale === "he-IL";
  const dir = isHebrew ? ' dir="rtl"' : "";
  const lang = isHebrew ? "he" : "en";

  const fontCss =
    buildFontFace("FrankRuhlLibre-Regular.ttf", "normal") +
    buildFontFace("FrankRuhlLibre-Bold.ttf", "bold");

  const rows = entries
    .map((entry, i) => {
      const bg = i % 2 === 0 ? ' style="background:#f9f6f1"' : "";
      return `<tr${bg}><td>${entry.hebrewYear}</td><td>${escapeHtml(entry.hebrewDate)}</td><td>${escapeHtml(formatGregorianDate(entry.gregorianDate, labels.dateLocale))}</td></tr>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="${lang}"${dir}>
<head><meta charset="UTF-8"><style>
${fontCss}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'FRLibre',Georgia,serif;color:#2d2318;background:#fff;font-size:11pt;padding:32px 28px}
.hdr{text-align:center;margin-bottom:28px}
.title{font-size:22pt;font-weight:bold;margin-bottom:8px}
.name{font-size:15pt;margin-bottom:5px}
.subhead{font-size:10pt;color:#8A7B6B}
table{width:100%;border-collapse:collapse;margin-bottom:24px}
thead th{font-weight:bold;font-size:10.5pt;padding:6px 8px;border-bottom:1.5px solid #c8bfb6;text-align:start}
tbody td{padding:5px 8px;font-size:10pt}
.footer{text-align:center;font-size:8.5pt;color:#999}
</style></head>
<body>
<div class="hdr">
  <div class="title">${escapeHtml(labels.title)}</div>
  <div class="name">${escapeHtml(name)}</div>
  <div class="subhead">${escapeHtml(labels.deathDatePrefix)} ${escapeHtml(hebrewDeathDate)}</div>
</div>
<table>
  <thead><tr>
    <th>${escapeHtml(labels.colYear)}</th>
    <th>${escapeHtml(labels.colHebrewDate)}</th>
    <th>${escapeHtml(labels.colGregorianDate)}</th>
  </tr></thead>
  <tbody>${rows}</tbody>
</table>
<div class="footer">${escapeHtml(labels.footer)}</div>
</body></html>`;
}

const MAC_CHROME =
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";

async function generatePDF(html: string): Promise<Uint8Array> {
  const isVercel = !!process.env.VERCEL;

  const executablePath =
    process.env.PUPPETEER_EXECUTABLE_PATH ??
    (!isVercel && process.platform === "darwin" && fs.existsSync(MAC_CHROME)
      ? MAC_CHROME
      : await chromium.executablePath());

  const browser = await puppeteer.launch({
    executablePath,
    args: isVercel
      ? chromium.args
      : ["--no-sandbox", "--disable-setuid-sandbox"],
    headless: "shell",
    defaultViewport: null,
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "domcontentloaded" });
    const pdf = await page.pdf({
      format: "A4",
      margin: { top: "25mm", right: "20mm", bottom: "25mm", left: "20mm" },
      printBackground: true,
    });
    return pdf;
  } finally {
    await browser.close();
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function GET(
  request: Request,
  { params }: { params: Promise<Params> }
) {
  const { id } = await params;
  const { searchParams } = new URL(request.url);
  const format = searchParams.get("format");

  if (format !== "ics" && format !== "pdf") {
    return NextResponse.json(
      { error: "format must be 'ics' or 'pdf'" },
      { status: 400 }
    );
  }

  const memorial = await prisma.memorial.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      dateOfDeath: true,
      deathAfterSunset: true,
      disabled: true,
    },
  });

  if (!memorial || memorial.disabled) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const rawLocale = searchParams.get("locale") ?? "en";
  const locale = rawLocale === "he" ? "he" : "en";
  const labels = locale === "he" ? HE_LABELS : EN_LABELS;

  const { HDate } = await import("@hebcal/core");
  let hd = new HDate(new Date(memorial.dateOfDeath));
  if (memorial.deathAfterSunset) hd = hd.next();
  const hebrewDeathDate = hd.render(locale);

  const entries = getYahrzeitDates(
    memorial.dateOfDeath,
    memorial.deathAfterSunset,
    15,
    locale
  );

  const safeName = memorial.name.replace(/[^a-z0-9]/gi, "_");

  if (format === "ics") {
    const ics = generateICS(memorial.id, memorial.name, entries);
    return new Response(ics, {
      headers: {
        "Content-Type": "text/calendar; charset=utf-8",
        "Content-Disposition": `attachment; filename="yahrzeit-${safeName}.ics"`,
      },
    });
  }

  // PDF
  const html = buildHtml(memorial.name, hebrewDeathDate, entries, labels);
  const pdfBuffer = await generatePDF(html);
  return new Response(new Uint8Array(pdfBuffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="yahrzeit-${safeName}.pdf"`,
    },
  });
}
