import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { prisma } from "@/lib/prisma";
import { getYahrzeitDates } from "@/lib/yahrzeit";

type Params = { id: string };

function formatGregorianDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function formatIcsDate(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}${m}${d}`;
}

function nextDay(date: Date): string {
  const next = new Date(date);
  next.setDate(next.getDate() + 1);
  return formatIcsDate(next);
}

function generateICS(
  memorialId: string,
  name: string,
  entries: ReturnType<typeof getYahrzeitDates>
): string {
  const dtstamp =
    new Date().toISOString().replace(/[-:.]/g, "").slice(0, 15) + "Z";

  const events = entries
    .map((entry, i) => {
      const dateStr = formatIcsDate(entry.gregorianDate);
      const endStr = nextDay(entry.gregorianDate);
      return [
        "BEGIN:VEVENT",
        `UID:yahrzeit-${memorialId}-${i}@forever-memorial`,
        `DTSTAMP:${dtstamp}`,
        `DTSTART;VALUE=DATE:${dateStr}`,
        `DTEND;VALUE=DATE:${endStr}`,
        `SUMMARY:Yahrzeit \u2014 ${name}`,
        `DESCRIPTION:${entry.hebrewDate}`,
        "END:VEVENT",
      ].join("\r\n");
    })
    .join("\r\n");

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Forever Memorial//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    events,
    "END:VCALENDAR",
  ].join("\r\n");
}

function generatePDF(
  name: string,
  hebrewDeathDate: string,
  entries: ReturnType<typeof getYahrzeitDates>
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Title
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("Yahrzeit Calendar", { align: "center" });
    doc.moveDown(0.4);
    doc
      .fontSize(16)
      .font("Helvetica")
      .text(name, { align: "center" });
    doc.moveDown(0.2);
    doc
      .fontSize(11)
      .fillColor("#666666")
      .text(`Hebrew date of passing: ${hebrewDeathDate}`, { align: "center" });
    doc.moveDown(1.2);

    // Column headers
    doc.fillColor("#000000").fontSize(11).font("Helvetica-Bold");
    const colYear = 50;
    const colHebrew = 130;
    const colGregorian = 280;

    doc.text("Year", colYear, doc.y, { continued: false, width: 70 });
    doc.moveUp();
    doc.text("Hebrew Date", colHebrew, doc.y, { continued: false, width: 140 });
    doc.moveUp();
    doc.text("Gregorian Date", colGregorian, doc.y, {
      continued: false,
      width: 270,
    });
    doc.moveDown(0.3);

    // Divider
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#cccccc")
      .stroke();
    doc.moveDown(0.4);

    // Rows
    doc.font("Helvetica").fontSize(10).fillColor("#000000");
    entries.forEach((entry, i) => {
      const rowY = doc.y;
      if (i % 2 === 0) {
        doc
          .rect(50, rowY - 3, 495, 18)
          .fillColor("#f9f6f1")
          .fill();
      }
      doc.fillColor("#000000");
      doc.text(String(entry.hebrewYear), colYear, rowY, {
        continued: false,
        width: 70,
      });
      doc.moveUp();
      doc.text(entry.hebrewDate, colHebrew, rowY, {
        continued: false,
        width: 140,
      });
      doc.moveUp();
      doc.text(formatGregorianDate(entry.gregorianDate), colGregorian, rowY, {
        continued: false,
        width: 270,
      });
      doc.moveDown(0.5);
    });

    // Footer
    doc.moveDown(1);
    doc
      .fontSize(9)
      .fillColor("#999999")
      .text(
        `Generated by Forever Memorial \u2022 ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
        { align: "center" }
      );

    doc.end();
  });
}

export async function GET(
  request: Request,
  { params }: { params: Promise<Params> }
) {
  const { id } = await params;
  const { searchParams } = new URL(request.url);
  const format = searchParams.get("format");

  if (format !== "ics" && format !== "pdf") {
    return NextResponse.json(
      { error: "format must be 'ics' or 'pdf'" },
      { status: 400 }
    );
  }

  const memorial = await prisma.memorial.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      dateOfDeath: true,
      deathAfterSunset: true,
      disabled: true,
    },
  });

  if (!memorial || memorial.disabled) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const { HDate } = await import("@hebcal/core");
  let hd = new HDate(new Date(memorial.dateOfDeath));
  if (memorial.deathAfterSunset) hd = hd.next();
  const hebrewDeathDate = hd.render("en");

  const entries = getYahrzeitDates(
    memorial.dateOfDeath,
    memorial.deathAfterSunset
  );

  const safeName = memorial.name.replace(/[^a-z0-9]/gi, "_");

  if (format === "ics") {
    const ics = generateICS(memorial.id, memorial.name, entries);
    return new Response(ics, {
      headers: {
        "Content-Type": "text/calendar; charset=utf-8",
        "Content-Disposition": `attachment; filename="yahrzeit-${safeName}.ics"`,
      },
    });
  }

  // PDF
  const pdfBuffer = await generatePDF(memorial.name, hebrewDeathDate, entries);
  return new Response(new Uint8Array(pdfBuffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="yahrzeit-${safeName}.pdf"`,
    },
  });
}
